version: '3.9'

services:
  whinx_nemo_engine:
    build: .
    volumes:
      - .:/whinx
    ports:
      - "5000:5000"
    command: python app.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 'all'
              capabilities: [ gpu ]